- name: html to pdf
  uses: LukaszLapaj/html-to-pdf-action@master
  with:
    htmlFile: ./public/index.html
    outputFile: ./public/guide_automated.pdf
    pdfOptions: '{"format": "US Letter", "margin": {"top": "0.25", "left": "0.25", "right": "0.25", "bottom": "0.25"}}'
